### ISSUE TITLE
Native ad Custom view.

### ISSUE THREAD

**Issue by taimoor522** [hardikkhunt905/ad_turbo#1]
Is it possible to create a native ad from the flutter side? What if I want to customize the native ad?

**Comment by Hardiklogistreak** [comment]
@taimoor522  How do you want to customize?

**Comment by taimoor522** [comment]
Changing button color, aligning content differently like placing button above

**Comment by Hardiklogistreak** [comment]
@taimoor522 for that you need to create your own xml file for native ad you can't do custom changes on ad_turbo lib
